### ISSUE TITLE
can't access CLI

### ISSUE THREAD

**Issue by LishuGupta652** [EllyMandliel/WebDumper#1]
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: EACCES: permission denied, mkdir '/hcu'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/hcu'
}

**Comment by EllyMandliel** [comment]
Hey Lishu, are you sure you have permissions to write to that route? Try to make sure🙏.
If this issue persists try to specify a full folder path (which you have permissions to write to).

**Comment by LishuGupta652** [comment]
Thanks for the support. Issue got resolved by changing the permissions.
