### ISSUE TITLE
This just deleted all my files!!!

### ISSUE THREAD

**Issue by ordzy** [EllyMandliel/WebDumper#4]
I ran this command
webdumper -u https://movieboxpro.app - C:\Users\user\Downloads
And then all of my files were gone, except a few folders, but it also deleted some of the folders too.
Please help ASAP.

**Comment by flckv** [comment]
maybe that '- ' in between the source and target? did you check your trash folder?

**Comment by ordzy** [comment]
yeah

**Comment by EllyMandliel** [comment]
Hey, please try to recover the files from the Trash Bin. For next time, please specify target directory, and not containing directory. For example, if you wish the result to be in downloads, use:
`webdumper -u https://movieboxpro.app/ - C:\Users\user\Downloads\movieboxprod`
