### ISSUE TITLE
WebDumper has absolutely ruined my life.

### ISSUE THREAD

**Issue by omrikurtz** [EllyMandliel/WebDumper#6]
My Downloads/ folder contained all of my precious photos of my grandma. Her facebook was hacked by Pakistani hackers and now I will never have my beautiful photos of grandmother.

But aside from that this is a great tool, thank you for this project. I am finally able to dumpster websites.

**Comment by EllyMandliel** [comment]
Dear my friend, I am sorry to hear that,
Please accept the following $2 amazon gift card as an apology for your experience: BBZNOTI
